version: '2.24.6-desktop.1'
volumes:
  pg_demo:

services:
  demo_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    volumes:
      - pg_demo:/var/lib/postgres/data
    ports:
      - "127.0.0.1:5433:5432"
#  app:
#    restart: always
#    build: .
#    ports:
#      - "127.0.0.1:8080:8080"
#    depends_on:
#      - demo_db
#    environment:
#      SPRING_DATASOURCE_URL: 'jdbc:postgresql://demo_db:5432/demo_db'
#      JAVA_OPTS: '-Xmx512m'