version: '3'
volumes:
  pg_demo:

services:
#  demo_db:
  postgres:
    image: postgres
    container_name: 'java-postgres'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    volumes:
      - pg_demo:/var/lib/postgres/data
    ports:
      - "127.0.0.1:5434:5432"
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "127.0.0.1:8080:8080"

    restart: always
#    depends_on:
#      - demo_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://demo_db:5432/demo_db'
      JAVA_OPTS: '-Xmx512m'